### ISSUE TITLE
Reimplementation

### ISSUE THREAD

**Issue by jonashaag** [artemrizhov/django-mail-templated#7]
https://github.com/jonashaag/django-mail-templated-simple

Just posting this here if someone else has issues with serialization or django-celery-email.

Maybe you could explain why you had to make your implementation so complicated? I'm not saying you should change it. Just wondering...

**Comment by artemrizhov** [comment]
Finally **mail_templated** was reimplemented too :)

**Comment by jonashaag** [comment]
I had a look at the reimplementation, and while it looks like some of the `render` related complexity has been cleaned up, the code still contains an insane amount stuff going on, most of which is non-trivial to understand.

How can you even come up with a solution so complicated for a problem so simple? Why do you need all that "change any parameters anytime later" flexibility? What do you even need state for? You see what sub classing Django's email class brings you there? Issues with integrating into other code, hence complexity.

Plus, the new `clean` parameter to `__init__` follows the principle of most surprise, because if `render=False, clean=True` is passed, then the class behaves as if `render=True`, without any kind of warning. The `render=False, clean=True` case should be illegal and throw an error. But you can get rid of this complexity simply by not making a subclass in the first place.

What common use cases are you trying to cover with all that complicated stuff in this library? Isn't the problem description simply "I don't want to have email templates in the Python code" or "I want an easy way to have multiple email templates to choose from"?

How come my implementation doesn't do any subclassing, doesn't have issues with integration into other code, doesn't invent any new interfaces, doesn't need state? It doesn't even contain any real case distinctions (`if` statements), because the problem it solves is trivial, so the solution should be trivial as well!

I'm in no position to tell what you should spend your time on, but from my perspective your solution is a giant waste of your lifetime. How many hours have you spent implementing all that stuff, trying to figure out all the corner cases, writing tests for all the cases, debugging incompatibilities with other software, etc? I have spent no more than a few hours on the whole project, and that includes reading up all of the mail-related Django documentation, setting up CI, publishing to PyPI etc.

Please tell my if my criticism annoys you, in which case I'll shut up and leave you alone :-)

**Comment by artemrizhov** [comment]
@jonashaag 
> I had a look at the reimplementation, and while it looks like some of the render related complexity has been cleaned up

Thanks to your previous criticism :)

> Plus, the new clean parameter to __init__ follows the principle of most surprise, because if render=False, clean=True is passed, then the class behaves as if render=True, without any kind of warning. The render=False, clean=True case should be illegal and throw an error.

You are right! Thanks. I've fixed this in the last version.

> But you can get rid of this complexity simply by not making a subclass in the first place.

No needs, this is done by you already ;)

> the code still contains an insane amount stuff going on, most of which is non-trivial to understand.

That's interesting. Actually, you should not understand the implementation. You should just understand how to use this. Are there any unclear things in the API?

What about other questions, well, you ask too many questions at once. I have answers for all of these questions, but do you really want to read them?

If you want to discuss this, let's review just one of many examples. Let's use your implementation to send 10000 email messages at once.

```python
class CompareAppsTestCase(TestCase):

    def test1(self):
        start = time()
        mail_templated_simple.send_mass_mail('email.tpl', tuple(
            ({'foo': foo}, 'inter@net.com', ['inter@net.com'])
            for foo in range(1000)))
        print 'mail_templated_simple: {}s'.format(time() - start)

    def test2(self):
        start = time()
        message = mail_templated.EmailMessage('email.tpl')
        for foo in range(1000):
            message.from_email, message.to = 'inter@net.com', ['inter@net.com']
            message.context = {'foo': foo}
        print 'mail_templated: {}s'.format(time() - start)

```

Result:
```
mail_templated_simple: 7.39179491997s
mail_templated: 0.00233292579651s
```

10000 is not a big number. Now imagine we send 1 million messages, and imagine we use some slow (and probably third-party) storage for the email templates.

The answer is that the developer who uses your app will need to reimplement either your app or storage class. My app is ready for this and many other situations. Just because it can (c)

**Comment by artemrizhov** [comment]
Heh, there was a small mistake in the example ))) Fixed.

**Comment by artemrizhov** [comment]
One thing that I'm really in doubt about is those arguments `render` and `clear`. While they are pretty simple, they add more ways to do same things. This seems like not a Python way. This is a kind of universal function that can cook and drive and do whatever you want. This is a bad design pattern. I'll probably remove them in the next version.

**Comment by artemrizhov** [comment]
Please let me know what you think about this change
https://github.com/artemrizhov/django-mail-templated/pull/22/files

**Comment by jonashaag** [comment]
> That's interesting. Actually, you should not understand the implementation. You should just understand how to use this. Are there any unclear things in the API?

I *always* have to look at the implementation of all third party code at some point in the project, either because it has bugs, behaviour I didn't expect (this case back in 2014), incomplete documentation (or haven't found it in the docs), … I usually do a quick check on the quality and complexity of all third party code just to be sure I don't make myself dependent on some badly designed API.

> What about other questions, well, you ask too many questions at once. I have answers for all of these questions, but do you really want to read them?

I do, best with examples for each, but I understand if you don't want to spend time explaining all that stuff to me.

> Now imagine we send 1 million messages, and imagine we use some slow (and probably third-party) storage for the email templates.

Note that this case hasn't been considered in my implementation yet, but it is trivial to fix: Add the ability to pass a loaded template.

```diff
- def email_message(template_name, …):
-    template = get_template(template_name)
+ def email_message(template, …):
+    if isinstance(template, str):
+        template = get_template(template)
```

In my benchmarks, this speeds up mail-templated-simple's performance from 4x slower to about 1.3x slower.

**Comment by artemrizhov** [comment]
> Note that this case hasn't been considered in my implementation yet, but it is trivial to fix: Add the ability to pass a loaded template.

Sure, all such thing are trivial to fix, because the task is simple and Python is almost perfect. I just wanted to show how (and why) you just added new condition to your code.

To be honest, I don't use mail_templated for a long time because it is not needed in my current projects. This is just a kind of pet project. It is small enough to do and finish tasks on a weekend, but it still gives me significant experience, mostly because I can finish work quickly and see the result. This is also why I tend to add features that probably are not needed for anybody ))) It is hard to understand what may be needed when you don't use this yourself. My actual goal is not covering all the cases, but making the app flexible enough so that all problems may be solved without modifying the source code. So feedbacks from another developers are very important for me. Thank you for your feedbacks.

**Comment by artemrizhov** [comment]
>> That's interesting. Actually, you should not understand the implementation. You should just understand how to use this. Are there any unclear things in the API?

> I always have to look at the implementation of all third party code at some point in the project

And yes, I realized that I was wrong on this statement. I usually check the code of third-party libs too, and for the same reasons. I just wanted to say that I'm focused on the API. What about the code, I'm always trying to do my best to make it good as much as possible :) I feel like if the **idea** of the API is clear, then my code should not be too complex to understand.
